<a href="https://colab.research.google.com/github/Guptarohit2003/Machine-Learning/blob/main/Tensorflow/Exercises/%F0%9F%9B%A0_00_TensorFlow_Fundamentals_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

### 1. Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant()`.

In [2]:
# Creating Scalar
scalar = tf.constant(8)
scalar, scalar.ndim, scalar.dtype

(<tf.Tensor: shape=(), dtype=int32, numpy=8>, 0, tf.int32)

In [3]:
# Creating Vectorr
vector = tf.constant([10,20])
vector, vector.ndim, vector.dtype

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 20], dtype=int32)>,
 1,
 tf.int32)

In [6]:
# Creating Matrix
matrix = tf.constant([[10,20],
                      [30, 40]])
matrix, matrix.ndim, matrix.dtype

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10, 20],
        [30, 40]], dtype=int32)>,
 2,
 tf.int32)

In [7]:
# Creating Tensor
tensor = tf.constant([[[10,20,30],
                       [40,50,60]],
                      [[60, 50, 40],
                      [30, 20, 10]]])
tensor, tensor.ndim, tensor.dtype

(<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
 array([[[10, 20, 30],
         [40, 50, 60]],
 
        [[60, 50, 40],
         [30, 20, 10]]], dtype=int32)>,
 3,
 tf.int32)

### 2. Find the shape, rank and size of the tensors you created in 1.

In [9]:
# For Tensor
tf.shape(tensor), tf.rank(tensor), tf.size(tensor)

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 2, 3], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=3>,
 <tf.Tensor: shape=(), dtype=int32, numpy=12>)

In [10]:
#In addition
#For scalar
scalar.shape, tf.rank(scalar), tf.size(scalar)

(TensorShape([]),
 <tf.Tensor: shape=(), dtype=int32, numpy=0>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>)

In [11]:
# For Vector
tf.shape(vector), tf.rank(vector),tf.size(vector)

(<tf.Tensor: shape=(1,), dtype=int32, numpy=array([2], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2>)

In [12]:
# For Matrix
tf.shape(matrix), tf.rank(matrix), tf.size(matrix)

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 2], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2>,
 <tf.Tensor: shape=(), dtype=int32, numpy=4>)

### 3. Create two tensors containing random values between 0 and 1 with shape `[5, 300]`

In [13]:
tf.random.set_seed(42)
tensor_one = tf.constant(tf.random.uniform([5,300],0,1))
tensor_two = tf.constant(tf.random.uniform([5,300],0,1))
tensor_one, tensor_two

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.6645621 , 0.44100678, 0.3528825 , ..., 0.31410468, 0.7593535 ,
         0.03699052],
        [0.532024  , 0.29129946, 0.10571766, ..., 0.54052293, 0.31425726,
         0.2200619 ],
        [0.08404207, 0.03614604, 0.97732127, ..., 0.21516645, 0.9786098 ,
         0.00726748],
        [0.7396945 , 0.6653172 , 0.0787828 , ..., 0.7117733 , 0.07013571,
         0.9409125 ],
        [0.15861344, 0.12024033, 0.27218235, ..., 0.8824879 , 0.1432488 ,
         0.44135118]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.68789124, 0.48447883, 0.9309944 , ..., 0.6920762 , 0.33180213,
         0.9212563 ],
        [0.27369928, 0.10631859, 0.6218617 , ..., 0.4382149 , 0.30427706,
         0.51477313],
        [0.00920248, 0.37280262, 0.8177401 , ..., 0.56786287, 0.49201214,
         0.9892651 ],
        [0.88608265, 0.08672249, 0.12160683, ..., 0.91770685, 0.72545695,
         0.8280058 ],
        [0.36690

### 4. Multiply the two tensors you created in 3 using matrix multiplication

In [15]:
mat_mul_1 = tf.matmul(tensor_one, tensor_two, transpose_a=True)
mat_mul_1

<tf.Tensor: shape=(300, 300), dtype=float32, numpy=
array([[1.317161  , 0.61993605, 1.2612379 , ..., 1.5290778 , 1.0735596 ,
        1.6227092 ],
       [1.0170685 , 0.42642498, 0.8181824 , ..., 1.1469344 , 0.8212255 ,
        1.1739546 ],
       [0.45034647, 0.8037954 , 1.4656199 , ..., 1.105671  , 0.88152766,
        1.481925  ],
       ...,
       [1.3204696 , 1.1634867 , 1.7423928 , ..., 1.8386563 , 1.5207756 ,
        1.5979093 ],
       [0.73207504, 0.90400356, 1.8493464 , ..., 1.3821819 , 0.98218614,
        1.924531  ],
       [1.0814031 , 0.5316744 , 0.7174167 , ..., 1.2942287 , 1.0804075 ,
        1.0476992 ]], dtype=float32)>

In [17]:
mat_mul_2 = tf.matmul(tensor_one,tensor_two, transpose_b=True)
mat_mul_2

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[80.33345 , 73.40498 , 77.159615, 73.98369 , 80.90053 ],
       [75.146355, 68.80437 , 74.24302 , 71.841835, 75.60206 ],
       [79.7594  , 75.644554, 77.797585, 74.74873 , 80.559845],
       [75.08526 , 69.064064, 74.30776 , 72.27616 , 76.05669 ],
       [85.05688 , 74.26627 , 78.00687 , 74.88679 , 83.13417 ]],
      dtype=float32)>

### 5. Multiply the two tensors you created in 3 using dot product.

In [20]:
dot_prduct = tf.tensordot(tensor_one, tf.transpose(tensor_two), axes = 1)
dot_prduct

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[80.33345 , 73.40498 , 77.159615, 73.98369 , 80.90053 ],
       [75.146355, 68.80437 , 74.24302 , 71.841835, 75.60206 ],
       [79.7594  , 75.644554, 77.797585, 74.74873 , 80.559845],
       [75.08526 , 69.064064, 74.30776 , 72.27616 , 76.05669 ],
       [85.05688 , 74.26627 , 78.00687 , 74.88679 , 83.13417 ]],
      dtype=float32)>

### 6. Create a tensor with random values between 0 and 1 with shape `[224, 224, 3]`.

In [21]:
tf.random.set_seed(42)
tensor_three = tf.random.uniform(shape = [224,224,3], minval=0,maxval=1)
tensor_three

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.6645621 , 0.44100678, 0.3528825 ],
        [0.46448255, 0.03366041, 0.68467236],
        [0.74011743, 0.8724445 , 0.22632635],
        ...,
        [0.42612267, 0.09686017, 0.16105258],
        [0.1487099 , 0.04513884, 0.9497483 ],
        [0.4393103 , 0.28527975, 0.96971095]],

       [[0.73308516, 0.5657046 , 0.33238935],
        [0.8838178 , 0.87544763, 0.56711245],
        [0.8879347 , 0.47661996, 0.42041814],
        ...,
        [0.7716515 , 0.9116473 , 0.3229897 ],
        [0.43050945, 0.83253574, 0.45549798],
        [0.29816985, 0.9639522 , 0.3316357 ]],

       [[0.41132426, 0.2179662 , 0.53570235],
        [0.5112119 , 0.6484759 , 0.8894886 ],
        [0.42459428, 0.20189774, 0.85781324],
        ...,
        [0.02888799, 0.3995477 , 0.11355484],
        [0.68524575, 0.04945195, 0.17778492],
        [0.97627187, 0.79811585, 0.9411576 ]],

       ...,

       [[0.9019445 , 0.27011132, 0.8090267 ],
        [0.32

### 7. Find the min and max values of the tensor you created in 6.

In [23]:
tf.reduce_max(tensor_three)

<tf.Tensor: shape=(), dtype=float32, numpy=0.999998>

In [24]:
tf.reduce_min(tensor_three)

<tf.Tensor: shape=(), dtype=float32, numpy=3.5762787e-07>

### 8. Created a tensor with random values of shape `[1, 224, 224, 3]` then squeeze it to change the shape to `[224, 224, 3]`.

In [26]:
tensor_four = tf.random.uniform(shape= [1, 224, 224, 3], minval= 0, maxval= 1)
tensor_four

<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
array([[[[0.7413678 , 0.62854624, 0.01738465],
         [0.3431449 , 0.51063764, 0.3777541 ],
         [0.07321596, 0.02137029, 0.2871771 ],
         ...,
         [0.98953485, 0.45382905, 0.2006687 ],
         [0.6295223 , 0.4937899 , 0.01816809],
         [0.95386636, 0.11542463, 0.85691285]],

        [[0.78435016, 0.7826872 , 0.87936425],
         [0.24906898, 0.3207239 , 0.10955775],
         [0.543224  , 0.7151396 , 0.40334642],
         ...,
         [0.2445668 , 0.01746976, 0.9036933 ],
         [0.02975535, 0.592268  , 0.9877522 ],
         [0.36701274, 0.33112562, 0.5638567 ]],

        [[0.15829337, 0.7288823 , 0.3366307 ],
         [0.70792687, 0.16910625, 0.9429966 ],
         [0.10120225, 0.5919596 , 0.8687303 ],
         ...,
         [0.28134012, 0.10011208, 0.37038183],
         [0.77874243, 0.05421627, 0.4664607 ],
         [0.2549187 , 0.7968637 , 0.83405185]],

        ...,

        [[0.32922816, 0.06343532, 

In [28]:
squeezed_tensor = tf.squeeze(tensor_four)
squeezed_tensor

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.7413678 , 0.62854624, 0.01738465],
        [0.3431449 , 0.51063764, 0.3777541 ],
        [0.07321596, 0.02137029, 0.2871771 ],
        ...,
        [0.98953485, 0.45382905, 0.2006687 ],
        [0.6295223 , 0.4937899 , 0.01816809],
        [0.95386636, 0.11542463, 0.85691285]],

       [[0.78435016, 0.7826872 , 0.87936425],
        [0.24906898, 0.3207239 , 0.10955775],
        [0.543224  , 0.7151396 , 0.40334642],
        ...,
        [0.2445668 , 0.01746976, 0.9036933 ],
        [0.02975535, 0.592268  , 0.9877522 ],
        [0.36701274, 0.33112562, 0.5638567 ]],

       [[0.15829337, 0.7288823 , 0.3366307 ],
        [0.70792687, 0.16910625, 0.9429966 ],
        [0.10120225, 0.5919596 , 0.8687303 ],
        ...,
        [0.28134012, 0.10011208, 0.37038183],
        [0.77874243, 0.05421627, 0.4664607 ],
        [0.2549187 , 0.7968637 , 0.83405185]],

       ...,

       [[0.32922816, 0.06343532, 0.23936498],
        [0.42

In [29]:
tf.reshape(tensor_four, [224, 224, 3])

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.7413678 , 0.62854624, 0.01738465],
        [0.3431449 , 0.51063764, 0.3777541 ],
        [0.07321596, 0.02137029, 0.2871771 ],
        ...,
        [0.98953485, 0.45382905, 0.2006687 ],
        [0.6295223 , 0.4937899 , 0.01816809],
        [0.95386636, 0.11542463, 0.85691285]],

       [[0.78435016, 0.7826872 , 0.87936425],
        [0.24906898, 0.3207239 , 0.10955775],
        [0.543224  , 0.7151396 , 0.40334642],
        ...,
        [0.2445668 , 0.01746976, 0.9036933 ],
        [0.02975535, 0.592268  , 0.9877522 ],
        [0.36701274, 0.33112562, 0.5638567 ]],

       [[0.15829337, 0.7288823 , 0.3366307 ],
        [0.70792687, 0.16910625, 0.9429966 ],
        [0.10120225, 0.5919596 , 0.8687303 ],
        ...,
        [0.28134012, 0.10011208, 0.37038183],
        [0.77874243, 0.05421627, 0.4664607 ],
        [0.2549187 , 0.7968637 , 0.83405185]],

       ...,

       [[0.32922816, 0.06343532, 0.23936498],
        [0.42

### 9. Create a tensor with shape `[10]` using your own choice of values, then find the index which has the maximum value.

In [36]:
tensor_five = tf.constant([10, 20, 0.09, 10.1, 23, 1, 13, 23.,-1, -0.003])
tensor_five.shape

TensorShape([10])

In [37]:
max_index = tf.argmax(tensor_five)
max_index, tensor_five[max_index]

(<tf.Tensor: shape=(), dtype=int64, numpy=4>,
 <tf.Tensor: shape=(), dtype=float32, numpy=23.0>)

### 10. One-hot encode the tensor you created in 9.

In [42]:
tensor_new  = tf.cast(tensor_five, dtype= tf.int32)
tf.one_hot(tensor_new, depth= 10), tensor_new

(<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
 array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>,
 <tf.Tensor: shape=(10,), dtype=int32, numpy=array([10, 20,  0, 10, 23,  1, 13, 23, -1,  0], dtype=int32)>)