# Introuction to Tensors

In [1]:
# Import Tensorflow
import tensorflow as tf
tf.__version__

'2.15.0'

In [2]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
scalar.ndim

0

In [4]:
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# Check the dimension of vector
vector.ndim

1

In [6]:
# create a matrix (has more than 1 dimension)
matrix = tf.constant([[15, 5],
                      [5, 15]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[15,  5],
       [ 5, 15]], dtype=int32)>

In [7]:
# Dimensions of matrix
matrix.ndim

2

In [8]:
# Create another matrix
another_matrix = tf.constant([[1,2],
                              [2,3],
                              [3,1]], dtype = tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [2., 3.],
       [3., 1.]], dtype=float16)>

In [9]:
# DImension of another matrix
another_matrix.ndim

2

In [10]:
# Let's create a tensor
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[4, 5, 6],
                       [1, 2, 3]],
                      [[3, 2, 1],
                      [6, 5, 4]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[4, 5, 6],
        [1, 2, 3]],

       [[3, 2, 1],
        [6, 5, 4]]], dtype=int32)>

In [11]:
tensor.ndim

3

What we've created so far

* Scalar : a single number
* Vector : a number with direction
* Matrix : a 2D array of numbers
* Tensor : an N-dimensional array of numbers

### Creating tensors with `tf.Variable`

In [12]:
changeable_tensor = tf.Variable([15, 5])
unchangeable_tensor = tf.constant([15, 5])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([15,  5], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([15,  5], dtype=int32)>)

In [13]:
# Changing one of the element
changeable_tensor[0] = 5
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [14]:
# using assign
changeable_tensor[0].assign(5)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 5], dtype=int32)>

In [15]:
unchangeable_tensor[1].assign(15)
unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

### Creating Random Tensors

Random Tensors are tensors with arbitary size which contain random numbers.

In [16]:
 random_1 = tf.random.Generator.from_seed(15)
 random_1 = random_1.normal(shape = (3,2))
 random_2 = tf.random.Generator.from_seed(15)
 random_2 = random_2.normal(shape = (3,2))

# Are they equal?

random_1 , random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.33149973, -0.5445254 ],
        [ 1.5222508 ,  0.59303206],
        [-0.63509274,  0.3703566 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.33149973, -0.5445254 ],
        [ 1.5222508 ,  0.59303206],
        [-0.63509274,  0.3703566 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a tensors

In [17]:
not_shuffled = tf.constant([[1,2],
                            [2,3],
                            [3,1]])
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 3],
       [1, 2],
       [3, 1]], dtype=int32)>

In [18]:
not_shuffled.ndim

2

**If both global and the operation seed are set both seeds are used in conjunction to determine the random sequence**

In [19]:
tf.random.set_seed(42)# global level seed
tf.random.shuffle(not_shuffled, seed=42) # Operation level seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [2, 3],
       [3, 1]], dtype=int32)>

### Other ways to make tensors

In [20]:
#create tensor of all ones
tf.ones([15,5])

<tf.Tensor: shape=(15, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [21]:
# Create tensors of all zeros
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Getting information from Tensor

* Shape
* Rank
* Axis of Rotation
* Size

In [22]:
#Create a rank 4 tensor
rank_4_tensor = tf.zeros(shape= [2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [23]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

### Indexing Tensors
DOne just like Python list

In [24]:
some_list = [1, 2, 3, 4]
some_list[:2]

[1, 2]

In [25]:
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [26]:
rank_2_tensor = tf.constant([[10, 7],
                             [2, 5]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5]], dtype=int32)>

In [27]:
# Add an extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 2],
        [ 5]]], dtype=int32)>

In [28]:
#Alternative
tf.expand_dims(rank_2_tensor, axis= -1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 2],
        [ 5]]], dtype=int32)>

### Manipulating tensors(Tensor Operation)

In [29]:
# we can add values to tensor using the addition operator ( Original Tensor will remain same)
tensor = tf.constant([[10,3],
                      [4, 11]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 13],
       [14, 21]], dtype=int32)>

In [30]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  30],
       [ 40, 110]], dtype=int32)>

In [31]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -7],
       [-6,  1]], dtype=int32)>

In [32]:
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  30],
       [ 40, 110]], dtype=int32)>

**Matrix Multiplication**

visit matrixmultiplication.xyz to visualise

In [33]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[112,  63],
       [ 84, 133]], dtype=int32)>

In [34]:
# Matrix multiplication with Python Operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[112,  63],
       [ 84, 133]], dtype=int32)>

In [35]:
# Let's create two new tensor
X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])

In [36]:
tf.matmul(X, Y)

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul] name: 

In [ ]:
# Let's change their shape
tf.reshape(Y, shape=(2,3))

In [37]:
X @ tf.reshape(Y, shape= (2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [38]:
tf.matmul(tf.reshape(X, shape=(2 ,3)), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [39]:
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

**The Dot product**

In [40]:
# Perform dot on X and Y
tf.tensordot(tf.transpose(X), Y, axes = 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [41]:
# Perform matrix multiplication between X and Y (transposed)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [42]:
# Perform matrix multiplication between X and Y (Reshape)
tf.matmul(X, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [43]:
# Check the values of Y, reshape Y and trnsposed Y
print("Normal Y:")
print(Y, '\n')

print("Y reshaped to (2,3):")
print(tf.reshape(Y, shape= (2,3)), '\n')

print('Y transposed: ')
print(tf.transpose(Y))

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2,3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed: 
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


# CHanging the datatype of a person

In [44]:
B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [45]:
C = tf.constant([7,10])
C.dtype

tf.int32

In [46]:
# change from float32 to float16
D = tf.cast(B, dtype=tf.float16)
D

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [47]:
E = tf.cast(C, dtype=tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>

 ### Aggregating Tensors

In [48]:
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [49]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Forms of Aggregation
* Get the maximum
* Get the Minimum
* Get the mean of a tensor
* Get the sum of a tensor

In [50]:
import numpy as np
E = tf.constant(np.random.randint(0,100,50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([41, 56, 12, 86, 47, 77, 20,  4, 38, 68, 25, 39, 34, 78, 95, 95, 62,
       58, 33, 74, 89,  8, 28, 20, 48, 57, 56, 73, 72, 38,  0, 57, 57, 82,
       19, 73, 66, 89, 46, 42, 76,  4, 13, 58, 73,  7, 16, 26, 77, 46])>

In [51]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [52]:
#Find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [53]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=95>

In [54]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=49>

In [55]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2458>

In [56]:
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=718>

In [57]:
tf.math.reduce_variance(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=718.33435>

In [58]:
tf.math.reduce_std(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=26.80176>

# Find the Positional maximum and minimum

In [59]:
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [60]:
# Find the positional max
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [61]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [62]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [63]:
# Find the positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [64]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### Squeezing a tensor


In [65]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape = (1, 1, 1, 1, 50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [66]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [67]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

### One-hot Encoding

In [68]:
#create a list of indices
some_list = [0, 1, 2, 3]

tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

### Squaring, Logging, square root

In [73]:
H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [74]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [75]:
tf.sqrt(tf.cast(H,dtype= tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [76]:
# Find log
tf.math.log(tf.cast(H, dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensor and NumPy

In [78]:
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [79]:
np.array(J)

array([ 3.,  7., 10.])

In [80]:
type(J.numpy())

numpy.ndarray

In [81]:
numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.])

numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

### Finding access to GPUs

In [1]:
import tensorflow as tf
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [3]:
!nvidia-smi

Tue Jan 23 17:58:12 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   53C    P8              10W /  70W |      3MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--