# Introuction to Tensors

In [1]:
# Import Tensorflow
import tensorflow as tf
tf.__version__

'2.15.0'

In [2]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
scalar.ndim

0

In [4]:
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# Check the dimension of vector
vector.ndim

1

In [6]:
# create a matrix (has more than 1 dimension)
matrix = tf.constant([[15, 5],
                      [5, 15]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[15,  5],
       [ 5, 15]], dtype=int32)>

In [7]:
# Dimensions of matrix
matrix.ndim

2

In [8]:
# Create another matrix
another_matrix = tf.constant([[1,2],
                              [2,3],
                              [3,1]], dtype = tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [2., 3.],
       [3., 1.]], dtype=float16)>

In [9]:
# DImension of another matrix
another_matrix.ndim

2

In [10]:
# Let's create a tensor
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[4, 5, 6],
                       [1, 2, 3]],
                      [[3, 2, 1],
                      [6, 5, 4]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[4, 5, 6],
        [1, 2, 3]],

       [[3, 2, 1],
        [6, 5, 4]]], dtype=int32)>

In [11]:
tensor.ndim

3

What we've created so far

* Scalar : a single number
* Vector : a number with direction
* Matrix : a 2D array of numbers
* Tensor : an N-dimensional array of numbers

### Creating tensors with `tf.Variable`

In [12]:
changeable_tensor = tf.Variable([15, 5])
unchangeable_tensor = tf.constant([15, 5])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([15,  5], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([15,  5], dtype=int32)>)

In [14]:
# Changing one of the element
changeable_tensor[0] = 5
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [ ]:
# using assign
changeable_tensor[0].assign(5)
changeable_tensor

In [15]:
unchangeable_tensor[1].assign(15)
unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

### Creating Random Tensors

Random Tensors are tensors with arbitary size which contain random numbers.

In [16]:
 random_1 = tf.random.Generator.from_seed(15)
 random_1 = random_1.normal(shape = (3,2))
 random_2 = tf.random.Generator.from_seed(15)
 random_2 = random_2.normal(shape = (3,2))

# Are they equal?

random_1 , random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.33149973, -0.5445254 ],
        [ 1.5222508 ,  0.59303206],
        [-0.63509274,  0.3703566 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.33149973, -0.5445254 ],
        [ 1.5222508 ,  0.59303206],
        [-0.63509274,  0.3703566 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a tensors

In [17]:
not_shuffled = tf.constant([[1,2],
                            [2,3],
                            [3,1]])
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 3],
       [3, 1],
       [1, 2]], dtype=int32)>

In [18]:
not_shuffled.ndim

2

**If both global and the operation seed are set both seeds are used in conjunction to determine the random sequence**

In [19]:
tf.random.set_seed(42)# global level seed
tf.random.shuffle(not_shuffled, seed=42) # Operation level seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [2, 3],
       [3, 1]], dtype=int32)>

### Other ways to make tensors

In [20]:
#create tensor of all ones
tf.ones([15,5])

<tf.Tensor: shape=(15, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [21]:
# Create tensors of all zeros
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Getting information from Tensor

* Shape
* Rank
* Axis of Rotation
* Size

In [22]:
#Create a rank 4 tensor
rank_4_tensor = tf.zeros(shape= [2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [23]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

### Indexing Tensors
DOne just like Python list

In [24]:
some_list = [1, 2, 3, 4]
some_list[:2]

[1, 2]

In [25]:
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [26]:
rank_2_tensor = tf.constant([[10, 7],
                             [2, 5]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5]], dtype=int32)>

In [27]:
# Add an extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 2],
        [ 5]]], dtype=int32)>

In [28]:
#Alternative
tf.expand_dims(rank_2_tensor, axis= -1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 2],
        [ 5]]], dtype=int32)>

### Manipulating tensors(Tensor Operation)

In [29]:
# we can add values to tensor using the addition operator ( Original Tensor will remain same)
tensor = tf.constant([[10,3],
                      [4, 11]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 13],
       [14, 21]], dtype=int32)>

In [30]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  30],
       [ 40, 110]], dtype=int32)>

In [31]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -7],
       [-6,  1]], dtype=int32)>

In [32]:
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  30],
       [ 40, 110]], dtype=int32)>

**Matrix Multiplication**

visit matrixmultiplication.xyz to visualise

In [33]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[112,  63],
       [ 84, 133]], dtype=int32)>

In [34]:
# Matrix multiplication with Python Operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[112,  63],
       [ 84, 133]], dtype=int32)>

In [35]:
# Let's create two new tensor
X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])

In [36]:
tf.matmul(X, Y)

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul] name: 

In [37]:
# Let's change their shape
tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [38]:
X @ tf.reshape(Y, shape= (2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [39]:
tf.matmul(tf.reshape(X, shape=(2 ,3)), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [41]:
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

**The Dot product**

In [42]:
# Perform dot on X and Y
tf.tensordot(tf.transpose(X), Y, axes = 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>